### ISSUE TITLE
Installs files into the wrong directory

### ISSUE THREAD

**Issue by yurivict** [loriab/pylibefp#6]
It installs
```
lib/pylibefp/__init__.py
lib/pylibefp/core.so
lib/pylibefp/extras.py
lib/pylibefp/metadata.py
lib/pylibefp/tests/addons.py
lib/pylibefp/tests/conftest.py
lib/pylibefp/tests/systems.py
lib/pylibefp/tests/test_coverage.py
lib/pylibefp/tests/test_dict.py
lib/pylibefp/tests/test_efpefp.py
lib/pylibefp/tests/test_libefp.py
lib/pylibefp/tests/test_opts.py
lib/pylibefp/tests/test_psi.py
lib/pylibefp/tests/test_scf.py
lib/pylibefp/tests/utils.py
lib/pylibefp/wrapper/__init__.py
lib/pylibefp/wrapper/exceptions.py
lib/pylibefp/wrapper/psiutil.py
lib/pylibefp/wrapper/wrapper.py
share/cmake/pylibefp/pylibefpConfig.cmake
share/cmake/pylibefp/pylibefpConfigVersion.cmake
share/cmake/pylibefp/pylibefpTargets-%%CMAKE_BUILD_TYPE%%.cmake
share/cmake/pylibefp/pylibefpTargets.cmake
```

It should install them into the ```sitelib``` directory: ```lib/python2.7/site-packages```
Besides, python binding shouldn't install cmake files.

**Comment by yurivict** [comment]
Python version and ```sitelibdir``` are readable from the python executable. You should add a cmake option ```PYTHON_CMD```, and read the rest from it.

**Comment by loriab** [comment]
One can use `-DPYMOD_INSTALL_LIBDIR=/python3.6/site-packages` to insert the appropriate spacer between "lib" and "pylibefp". Not the most elegant, but it makes for convenient shifting between linux-style (everything under CMAKE_INSTALL_PREFIX, no need for site-packages buffer) and python-style (everything in active python's site-packages) installations.

Considering there's a compiled component to the package and also a dependency on another C library (libefp) and transitively lapack dependence, cmake config files seem reasonable to me.

Why `PYTHON_CMD` instead of the ordinary CMake `PYTHON_EXECUTABLE`? The py version is definitely read from the py exe. I'll add it the version-dependent cpython extension (instead of plain `.so`) shortly. The site-packages spacer I'm not keen to do, for flexibility reasons mentioned above.

**Comment by yurivict** [comment]
```PYTHON_EXECUTABLE``` is also fine.
> One can use -DPYMOD_INSTALL_LIBDIR=/python3.6/site-packages to insert the appropriate spacer between "lib" and "pylibefp". 

The spacer is fixed, though. All python modules are installed into either the system dir, or  user dir. These dirs are readable from the python executable.

**Comment by loriab** [comment]
Yes, if you're installing into the active python's site-packages, the spacer is fixed. Two things aren't fixed, though: (1) whether you're installing into the active python's site-packages or performing a traditional linux installation into `CMAKE_INSTALL_PREFIX` and (2) if the latter, whether you care about the python heritage that adds two extra directories under lib or you'd be content with the simpler lib/pylibefp and let the loading package or yourself manipulate PYTHONPATH.

It's probably strange to one who understands the different languages' native install patterns, but 99% of pylibefp (or psi4) installations just use (2) so `CMAKE_INSTALL_PREFIX` and default `PYMOD_INSTALL_LIBDIR=/` works out of the box. Case (1) is mostly for packaging and setting `CMAKE_INSTALL_PREFIX=dir-of-$PYTHON_EXECUTABLE/../lib` and `PYMOD_INSTALL_LIBDIR=/python3.6/site-packages` etc. suffices.

**Comment by yurivict** [comment]
Ok, thank you for this information. I still install it into the traditional system-wide directory.
